In [21]:
#import libraries

In [22]:
from keras.preprocessing.text import one_hot

In [23]:
# intialize sentence

In [24]:
sent = ['the glass of mile',
       'the glass of juice',
       'the cup of tea',
       'i am a good boy',
       'i am a good developer',
       'understand the meaning of words',
       'your videos are good']

In [25]:
sent

['the glass of mile',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [26]:
# vocabulary size 
voc_size = 1000

In [27]:
# one hot representation of words

In [28]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[215, 721, 168, 531], [215, 721, 168, 15], [215, 279, 168, 870], [454, 518, 181, 535, 600], [454, 518, 181, 535, 689], [361, 215, 735, 168, 434], [277, 963, 830, 535]]


In [29]:
# word embedding representation

In [30]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [31]:
import numpy as np

In [32]:
sent_length= 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen= sent_length)
print(embedded_docs)

[[  0   0   0   0 215 721 168 531]
 [  0   0   0   0 215 721 168  15]
 [  0   0   0   0 215 279 168 870]
 [  0   0   0 454 518 181 535 600]
 [  0   0   0 454 518 181 535 689]
 [  0   0   0 361 215 735 168 434]
 [  0   0   0   0 277 963 830 535]]


In [33]:
dim = 15

In [37]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [38]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 8, 15)             15000     
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [40]:
embedded_docs[0]

array([  0,   0,   0,   0, 215, 721, 168, 531])

In [41]:
print(model.predict(embedded_docs))

[[[ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [-0.04513779  0.03302813 -0.01346362  0.03023044  0.01620403
    0.03583605 -0.01683509 -0.00834453  0.00055498  0.01852931
   -0.02534012 -0.02599751 -0.03415457  0.01917217  0.04379827]
  [-0.02676072  0.03438026  0.03839942  0.03687981

In [43]:
print(model.predict(embedded_docs))

[[[ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [ 0.02423661 -0.03221699  0.01385519 -0.0204406   0.01896432
    0.00627031 -0.00031336  0.03078253 -0.01857115  0.03752606
    0.0001101  -0.00854112 -0.03444228 -0.02497573  0.03682328]
  [-0.04513779  0.03302813 -0.01346362  0.03023044  0.01620403
    0.03583605 -0.01683509 -0.00834453  0.00055498  0.01852931
   -0.02534012 -0.02599751 -0.03415457  0.01917217  0.04379827]
  [-0.02676072  0.03438026  0.03839942  0.03687981